
insert into ACCOUNTS_MGMT(ACCOUNT_ID,ACCOUND_STATUS,ADDRESS,BALANCE,FIRST_NAME,LAST_NAME )
values(123455,true,'Bengaluru',46211.2,'Sharath','Linga');
insert into ACCOUNTS_MGMT(ACCOUNT_ID,ACCOUND_STATUS,ADDRESS,BALANCE,FIRST_NAME,LAST_NAME )
values(123457,true,'Nizamabad',23211.2,'Raviteja','Linga');
insert into ACCOUNTS_MGMT(ACCOUNT_ID,ACCOUND_STATUS,ADDRESS,BALANCE,FIRST_NAME,LAST_NAME )
values(123458,true,'Mysuru',23241.2,'Shruthi','M');
insert into ACCOUNTS_MGMT(ACCOUNT_ID,ACCOUND_STATUS,ADDRESS,BALANCE,FIRST_NAME,LAST_NAME )
values(123459,true,'Nizamabad',26211.2,'Narahari','Linga');